# Generated by Django 2.2.13 on 2020-09-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='timezone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
