# Generated by Django 2.2.6 on 2019-12-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191024_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slack_team_id',
            field=models.CharField(default='T41DZFW4T', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slack_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
