# Generated by Django 2.2 on 2020-04-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
