# Generated by Django 2.2.10 on 2020-05-12 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0015_auto_20200512_2233'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200414_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('slack_id', models.CharField(max_length=20, null=True, unique=True)),
                ('slack_team_id', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('real_name', models.CharField(max_length=100)),
                ('topics_to_learn', models.CharField(max_length=1500)),
                ('topics_to_share', models.CharField(max_length=1500)),
                ('how_you_learned_about_pennyu', models.CharField(max_length=500)),
                ('metro_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_profiles', to=settings.AUTH_USER_MODEL)),  # noqa
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
