# Generated by Django 2.2.13 on 2020-09-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_is_verified'),
        ('pennychat', '0003_pennychat_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=20, unique=True)),
                ('slack_team_id', models.CharField(max_length=20)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SocialProfile')),
                ('topic_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.TopicChannel')),  # noqa
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=20)),
                ('penny_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pennychat.PennyChat')),  # noqa
                ('profiles', models.ManyToManyField(to='users.SocialProfile')),
                ('topic_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.TopicChannel')),  # noqa
            ],
        ),
    ]
