const Actions = {
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_MODAL: 'OPEN_MODAL',
}

const ModalNames = {
  AUTH_EMAIL: 'AUTH_EMAIL',
  AUTH_PASSWORD: 'AUTH_PASSWORD',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  SETTINGS: 'SETTINGS',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
}

export {
  ModalNames,
}

export default Actions
