# Generated by Django 2.2.5 on 2019-09-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20190715_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PennyChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('template_timestamp', models.FloatField()),
                ('template_channel', models.TextField()),
            ],
        ),
    ]
