# Generated by Django 2.2.5 on 2019-09-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_pennychat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pennychat',
            name='invitees',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
