# Generated by Django 2.2.5 on 2019-09-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_pennychat_invitees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pennychat',
            name='template_timestamp',
            field=models.TextField(),
        ),
    ]
