# Generated by Django 2.2.5 on 2019-09-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_pennychat_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='pennychat',
            name='view',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
