# Generated by Django 2.2.5 on 2019-09-29 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_pennychat_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='pennychat',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
