# Generated by Django 2.2.5 on 2019-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_pennychat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pennychat',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
