# Generated by Django 2.2.5 on 2019-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20190930_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pennychat',
            name='user',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pennychat',
            name='user_tz',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
