# Generated by Django 2.2.5 on 2019-10-09 00:40

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20191006_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pennychat',
            name='template_timestamp',
        ),
        migrations.AddField(
            model_name='pennychat',
            name='status',
            field=models.CharField(choices=[(bot.models.ChatStatus('Draft'), 'Draft'), (bot.models.ChatStatus('Shared'), 'Shared'), (bot.models.ChatStatus('In Progress'), 'In Progress'), (bot.models.ChatStatus('Completed'), 'Completed')], default='SH', max_length=2),
            preserve_default=False,
        ),
    ]
