# Generated by Django 2.2.10 on 2020-05-15 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PennyChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(10, 'Draft'), (20, 'Shared'), (25, 'Reminded'), (30, 'Completed'), (40, 'Abandoned')], default=10)),  # noqa
                ('created_from_slack_team_id', models.CharField(max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PennyChatSlackInvitation',
            fields=[
                ('penny_chat', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='invitation', serialize=False, to='pennychat.PennyChat')),  # noqa
                ('view', models.TextField()),
                ('organizer_tz', models.TextField()),
                ('organizer_slack_id', models.TextField(null=True)),
                ('invitees', models.TextField()),
                ('channels', models.TextField()),
                ('shares', models.TextField(null=True)),
            ],
            bases=('pennychat.pennychat',),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('penny_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='pennychat.PennyChat')),  # noqa
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),  # noqa
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(10, 'Organizer'), (20, 'Attendee')])),
                ('penny_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pennychat.PennyChat')),  # noqa
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to=settings.AUTH_USER_MODEL)),  # noqa
            ],
            options={
                'ordering': ['role'],
                'unique_together': {('penny_chat', 'user')},
            },
        ),
    ]
