# Generated by Django 2.2.5 on 2019-10-15 01:35

from django.db import migrations, models
import pennychat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PennyChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('invitees', models.TextField()),
                ('channels', models.TextField()),
                ('view', models.TextField()),
                ('user', models.TextField()),
                ('user_tz', models.TextField()),
                ('template_channel', models.TextField()),
                ('status', models.CharField(choices=[(pennychat.models.ChatStatus('Draft'), 'Draft'), (pennychat.models.ChatStatus('Shared'), 'Shared'), (pennychat.models.ChatStatus('In Progress'), 'In Progress'), (pennychat.models.ChatStatus('Completed'), 'Completed')], max_length=2)),
            ],
        ),
    ]
