# Generated by Django 2.2.5 on 2019-10-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PennyChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('invitees', models.TextField()),
                ('channels', models.TextField()),
                ('view', models.TextField()),
                ('user', models.TextField()),
                ('user_tz', models.TextField()),
                ('template_channel', models.TextField()),
                ('status', models.CharField(choices=[(1, 'Draft'), (2, 'Shared')], default=1, max_length=2)),
            ],
        ),
    ]
