# Generated by Django 2.2.6 on 2019-11-28 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.TextField()),
                ('penny_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='pennychat.PennyChat')),  # noqa
            ],
        ),
    ]
