# Generated by Django 2.2.5 on 2019-11-12 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0002_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
