# Generated by Django 2.2.13 on 2020-08-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0002_followup_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='pennychat',
            name='visibility',
            field=models.IntegerField(choices=[(10, 'Public'), (20, 'Private')], default=10),
        ),
    ]
