# Generated by Django 2.2.6 on 2019-12-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0002_followup'),
        ('users', '0003_auto_20191209_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='users.UserProfile'),  # noqa
        ),
        migrations.AlterField(
            model_name='pennychat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='users.UserProfile'),  # noqa
        ),
    ]
