# Generated by Django 2.2.5 on 2019-11-21 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0003_auto_20191112_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='penny_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='pennychat.PennyChat'),
        ),
    ]
