# Generated by Django 2.2.13 on 2020-11-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0003_pennychat_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='pennychat',
            name='video_conference_link',
            field=models.TextField(null=True),
        ),
    ]
