# Generated by Django 2.2.6 on 2020-01-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0003_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='type',
            new_name='role',
        ),
    ]
