# Generated by Django 2.2.6 on 2020-01-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0004_auto_20200106_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pennychat',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Shared'), (3, 'Completed')], default=1),
        ),
    ]
