# Generated by Django 2.2.6 on 2019-12-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0005_auto_20191223_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.IntegerField(choices=[(1, 'Organizer'), (2, 'Attendee'), (3, 'Invitee')], default=3),
        ),
    ]
