# Generated by Django 2.2.6 on 2020-02-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0006_auto_20200129_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pennychat',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='pennychat',
            name='invitees',
        ),
        migrations.RemoveField(
            model_name='pennychat',
            name='template_channel',
        ),
        migrations.RemoveField(
            model_name='pennychat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pennychat',
            name='user_tz',
        ),
        migrations.RemoveField(
            model_name='pennychat',
            name='view',
        ),
        migrations.AlterField(
            model_name='pennychat',
            name='status',
            field=models.IntegerField(choices=[(20, 'Shared'), (30, 'Completed'), (40, 'Abandoned')], default=20),
        ),
        migrations.CreateModel(
            name='PennyChatInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(10, 'Draft'), (20, 'Shared')], default=10)),
                ('user_tz', models.TextField()),
                ('template_channel', models.TextField()),
                ('view', models.TextField()),
                ('user', models.TextField(null=True)),
                ('invitees', models.TextField()),
                ('channels', models.TextField()),
                ('penny_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='pennychat.PennyChat')),  # noqa
            ],
        ),
    ]
