# Generated by Django 2.2.6 on 2020-02-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0007_auto_20200210_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pennychatinvitation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pennychatinvitation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pennychatinvitation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pennychatinvitation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pennychatinvitation',
            name='title',
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.IntegerField(choices=[(10, 'Organizer'), (20, 'Attendee'), (30, 'Invitee'), (40, 'Invited NonAttendee')], default=30),  # noqa
        ),
        migrations.AlterField(
            model_name='pennychat',
            name='status',
            field=models.IntegerField(choices=[(10, 'Draft'), (20, 'Shared'), (30, 'Completed'), (40, 'Abandoned')], default=10),  # noqa
        ),
        migrations.AlterField(
            model_name='pennychatinvitation',
            name='penny_chat',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='invitation', serialize=False, to='pennychat.PennyChat'),  # noqa
        ),
    ]
