# Generated by Django 2.2.6 on 2020-02-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0008_delete_penny_chat_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PennyChatInvitation',
            fields=[
                ('penny_chat', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='invitation', serialize=False, to='pennychat.PennyChat')),  # noqa
                ('user_tz', models.TextField()),
                ('template_channel', models.TextField()),
                ('view', models.TextField()),
                ('user', models.TextField(null=True)),
                ('invitees', models.TextField()),
                ('channels', models.TextField()),
            ],
            bases=('pennychat.pennychat',),
        ),
    ]
