# Generated by Django 3.0.3 on 2020-03-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0010_auto_20200227_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.IntegerField(choices=[(10, 'Organizer'), (20, 'Attendee')]),
        ),
    ]
