# Generated by Django 3.0.3 on 2020-03-15 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0011_auto_20200301_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantInvitation',
            fields=[
                ('participant', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='invitation', serialize=False, to='pennychat.Participant')),  # noqa
                ('scheduled_message_id', models.TextField()),
            ],
            bases=('pennychat.participant',),
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['role']},
        ),
    ]
