# Generated by Django 2.2.5 on 2020-03-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0011_auto_20200301_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['role']},
        ),
    ]
