# Generated by Django 2.2.5 on 2020-03-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_user'),
        ('pennychat', '0012_auto_20200308_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('penny_chat', 'user_profile')},
        ),
    ]
