# Generated by Django 2.2.10 on 2020-04-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennychat', '0013_auto_20200328_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pennychat',
            name='status',
            field=models.IntegerField(choices=[(10, 'Draft'), (20, 'Shared'), (25, 'Reminded'), (30, 'Completed'), (40, 'Abandoned')], default=10),  # noqa
        ),
    ]
