# Generated by Django 2.2.10 on 2020-05-12 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pennychat', '0014_auto_20200416_0238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PennyChatInvitation',
            new_name='PennyChatSlackInvitation',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to=settings.AUTH_USER_MODEL),  # noqa
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to=settings.AUTH_USER_MODEL),  # noqa
        ),
        migrations.AddField(
            model_name='pennychat',
            name='created_from_slack_team_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('penny_chat', 'user')},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user_profile',
        ),
    ]
